# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41f161653e4f18edce640a17f96f0ea4b72db037d1c099786cb940e68d10f533836bb71b75e860e78441a8b612dd3969d246b4c3291d6b046c210037d01e2282

test:
  secret_key_base: edafa6633a2de5d740cc7cba53f82accac7c55e7a3e0dc04c8a70b68fbfbe87b4848f49a183de294ae12afff5a9166e58e5e165ebf26f781096ed06329195d3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
